### PR TITLE
Update cssdb.json

### PR DESCRIPTION
**Pull request by trusktr**
I'm not sure if we're supposed to automate this, but this is the Nesting support (yay!). How do we keep cssdb up to date automatically?

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
@trusktr thanks for opening this! This data wasn't linked yet, looking at this now

**Comment by romainmenke** [comment]
That data is bogus :/

What shipped in browsers doesn't match the specification.
Some people working for browsers were very pushy on caniuse and pushed this through even when they were shipping something that was incomplete/wrong.

We can not mark any browser as supporting nesting.
Maybe Firefox will ship something correct.

**Comment by Antonio-Laguna** [comment]
Agreed with @romainmenke I was linking to caniuse and then realised that it didn't match the reality.

@trusktr in any case this change would need to go to `cssdb.settings.json` and then `npm run populatedb` takes care of updating all places that it needs

**Comment by romainmenke** [comment]
I am really hoping that Firefox ships soon and that it is actually correct.
This would give sufficient reason to correct the data on caniuse/mdn and overrule the persons working for browsers.

At that point we can :
- mark Safari and Chrome as partial implementations
- mark Firefox as a full implementation
- file bugs with both Safari and Chrome

**Comment by romainmenke** [comment]
Firefox seems to be on the right track : https://wpt.fyi/results/css/css-nesting/nesting-type-selector.html?label=master&label=experimental&aligned

But they have other issues : https://wpt.fyi/results/css/css-nesting?label=master&label=experimental&aligned

**Comment by romainmenke** [comment]
I've updated MDN so that Chrome and Safari are now correctly listed as partial implementations and this is also visible on caniuse : https://caniuse.com/mdn-css_selectors_nesting

I've made the needed changes here to track the MDN data going forward.
When Chrome and Safari ship a full implementation they will also be listed as such here :)

So unfortunately this will appear as a noop for a while longer.

Thank you for your contribution @trusktr 🎉

**Pull request merged**
