### PR TITLE
Stages are updated

### PR DESCRIPTION
**Pull request by yepninja**

### CODE REVIEW

**Comment by jonathantneal** [comment]
Without any description, I can’t verify this request. Also, color-mod is rejected. We can’t just add things we want.

**Comment by yepninja** [comment]
Thank you for quick reaction.
I've updated staged according to specifications of the features.

**Comment by yepninja** [comment]
- `CSS Color Module Level 4` is `Working Draft` now
- `CSS Fonts Module Level 3` is `Recommendation`

**Comment by jonathantneal** [comment]
@yepninja, I’m pretty sure color-mod is deprecated. Can you show me the latest commits that or github issues from the csswg to back up the color-mod change?

**Comment by jonathantneal** [comment]
Closing due to inactivity after my last question.

**Pull request closed without merging**
