### PR TITLE
add baseline support

### PR DESCRIPTION
**Pull request by romainmenke**
Baseline has an updated definition and I really like the result : https://developer.mozilla.org/en-US/blog/baseline-evolution-on-mdn/

This data is purely informational at this time.
I think it will be helpful to educate users that they still need a plugin for feature X or Y even when all browsers support it.

Changes :
- `interoperable_at` field in the npm package for each feature
- Baseline status icons on the cssdb site
- Baseline status badge as svg for each feature

_These won't auto-update, so we might need to think about scheduling some workflows here, but we can optimize this later. We have regular maintenance changes for dependencies anyway._

Screenshot 2023-12-25 at 14 29 09

### CODE REVIEW

**Comment by romainmenke** [comment]
@Antonio-Laguna I wanted to make use of these in `postcss-plugins`, but any feedback is welcome :)

**Comment by captainbrosset** [comment]
@romainmenke Hey! This is Patrick, from the W3C WebDX group. We interacted briefly on some of the issues on the https://github.com/web-platform-dx/web-features repository where the group is discussing various Baseline considerations.
At our last CG meeting, we agreed that we would love to have you over at one of our next group meetings to talk about your experience with Baseline in cssdb.

We would love to learn more about the cssdb project, the baseline feature you added to it, how you calculate it, and what data you might need from us.

If this sounds like something you'd be willing to do, I can invite you at one of our next meetings.

**Comment by romainmenke** [comment]
Hi @captainbrosset,

Happy to join a call!

I will also open an issue about cssdb at https://github.com/web-platform-dx/web-features
Then I can already document a bit what cssdb is and how baseline comes into play.

**Comment by captainbrosset** [comment]
@romainmenke I see you're already in the group: https://www.w3.org/groups/cg/webdx/participants/ so in theory, you should be able to get our meeting details from the shared calendar at: https://www.w3.org/groups/cg/webdx/calendar/
How about joining our Baseline call on March 7?

**Comment by romainmenke** [comment]
March 7 works for me, I'll attend that Baseline call.

**Pull request merged**
